// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package turtleDB

// rTxn is a read transaction
type rTxn struct {
	// Original buckets
	*buckets
}

func (r *rTxn) clear() {
	r.buckets = nil
}
